name: Auto Merge on Label

on:
  pull_request:
    types: [labeled]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge into QA
        if: github.event.label.name == 'merge-to-qa'
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'you@example.com'
          git remote add upstream https://github.com/documentos-digitales-lab/pruebas-prs.git
          git fetch upstream
          git checkout -b auto-merge/$GITHUB_HEAD_REF upstream/main
          git merge --no-ff $GITHUB_HEAD_REF
          git push upstream auto-merge/$GITHUB_HEAD_REF:QA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
