name: Merge PR Changes to Main Branches

on:
  pull_request:
    branches:
      - main

jobs:
  merge_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get PR URL
        id: pr_url
        run: echo "PR_URL=https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Merge changes based on PR labels
        run: |
          # Check PR labels
          labels=$(curl -s "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" | jq -r '.[].name')

          # Merge changes based on labels
          if [[ $labels == *"merge-to-develop"* ]]; then
            git checkout develop
            git merge ${{ github.event.pull_request.head.sha }} --no-edit
            git push
          fi

          if [[ $labels == *"merge-to-QA"* ]]; then
            git checkout QA
            git merge ${{ github.event.pull_request.head.sha }} --no-edit
            git push
          fi
