name: Merge PR Changes to Main Branches

on:
  pull_request:
    branches:
      - main

jobs:
  merge_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Merge changes based on PR labels
        run: |
          # Check PR labels
          label=$(curl -s "${{ github.event.pull_request.url }}/labels")
          echo $label
          labels=$(curl -s "${{ github.event.pull_request.url }}/labels" | jq -r '.[].name')
          echo "LABELS"
          echo $labels

          # Merge changes based on labels
          if [[ $labels == *"merge-to-develop"* ]]; then
            git checkout develop
            git merge ${{ github.event.pull_request.head.sha }} --no-edit
            git push
          fi

          if [[ $labels == *"merge-to-qa"* ]]; then
            git checkout QA
            git merge ${{ github.event.pull_request.head.sha }} --no-edit
            git push
          fi
